CMAKE_MINIMUM_REQUIRED(VERSION 3.24 FATAL_ERROR)

PROJECT(pbf LANGUAGES CXX CUDA)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

FILE(GLOB_RECURSE SOURCES
	"src/*.cpp"
	"src/**/*.cpp"
	"src/*.cu"
	"src/**/*.cu"
)
FILE(GLOB_RECURSE HEADERS
	"src/*.h"
	"src/**/*.h"
	"src/*.cuh"
	"src/**/*.cuh"
)
FILE(GLOB_RECURSE GLSL
	"resources/*.glsl"
	"resources/**/*.glsl"
)


ADD_EXECUTABLE(${CMAKE_PROJECT_NAME} ${SOURCES} ${HEADERS} ${GLSL})

SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES CXX_STANDARD 20)
SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES CUDA_ARCHITECTURES native)
SET_TARGET_PROPERTIES(${CMAKE_PROJECT_NAME} PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
SET(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)

TARGET_COMPILE_OPTIONS(${CMAKE_PROJECT_NAME} PUBLIC
	-Wall
	-Wextra
	-DGLEW_STATIC
	# glm has device attributes on default constructors; suppress warnings
	-Xcudafe --diag_suppress=20012
)

TARGET_COMPILE_OPTIONS(${CMAKE_PROJECT_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:
	--generate-line-info
	--use_fast_math
	--relocatable-device-code=true
	--extended-lambda
	--expt-relaxed-constexpr>)

find_package(OpenGL REQUIRED)
FIND_PACKAGE(GLEW REQUIRED)
FIND_PACKAGE(glm REQUIRED)
FIND_PACKAGE(glfw3 3.3 REQUIRED)
TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME} PRIVATE OpenGL::GL ${GLEW_LIBRARIES} glm::glm glfw)


INCLUDE_DIRECTORIES(
	src
	${GLEW_INCLUDE_DIRECTORIES})
